version: '3.8'

services:
  # Development service
  flux-tube-dev:
    build:
      context: .
      target: development
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=development
      - PORT=5000
    volumes:
      - .:/app
      - /app/node_modules
    command: npm start
    profiles:
      - dev

  # Production service
  flux-tube-prod:
    build:
      context: .
      target: production
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=production
      - PORT=5000
    restart: unless-stopped
    profiles:
      - prod

  # Production service with custom port
  flux-tube-custom:
    build:
      context: .
      target: production
    ports:
      - "3000:5000"
    environment:
      - NODE_ENV=production
      - PORT=5000
    restart: unless-stopped
    profiles:
      - custom
